// components/bio.tsx
import React from "react";
import DecorativeBackground from "./decorative-background";

interface BioProps {
  title: string;
  paragraphs: readonly string[];
}

export default function Bio({ title, paragraphs }: BioProps) {
  return (
    <div className="rounded-2xl shadow-md p-6 hover:shadow-lg transition-all duration-500 relative group overflow-hidden bg-white hover:rotate-2 hover:scale-105 transform text-gray-900">
      <DecorativeBackground color="bg-green-500" count={5} />
      <p className="font-medium mb-2 text-gray-900 relative z-10">{title}</p>
      {paragraphs.map((paragraph, index) => (
        <p key={index} className="mt-2 text-gray-900 relative z-10">
          {paragraph}
        </p>
      ))}
    </div>
  );
}

// components/Bio.vue
<template>
  <div
    class="
      rounded-2xl
      shadow-md
      p-4
      hover:shadow-lg
      transition
      duration-500
      relative
      group
      overflow-hidden
	  transform
	  hover:rotate-2
	  hover:scale-105
    "
  >
    <p>{{bio.title}}</p>
    <p class="mt-2" v-for="(paragraph, index) in bio.paragraphs" :key="index">
      {{paragraph}}
    </p>
    <BackgroundFigure v-for="n in 5" :key="n" color="bg-green-500" />
  </div>
</template>

<script>
export default {
  props: {
    bio: {
      type: Object,
      default: function () {
        return {};
      },
    },
  },
};
</script>
